###used to install a list of packages###
- hosts: cc1
  tasks:
  - include: apt_get_update.yml
  - name: Install apt packages
    apt:
      pkg: "{{ item }}"
      state: latest
      force: yes
    register: install_packages
    until: install_packages|success
    sudo: yes
    with_items:
     - python-debtcollector
     - python-psutil
     - python-jinja2
     - python-lxml
     - python-rfc3986
     - python-boto
     - python-neutronclient
     - python-cinderclient
     - glance
     - glance-api
     - glance-common
     - glance-registry
     - python-oslo.rootwrap 
     - nova-api
     - nova-cert
     - nova-common
     - nova-consoleauth
     - nova-novncproxy
     - python-glance
     - python-glanceclient
     - python-nova
     - python-novaclient
     - python-oslo-log
     - python-oslo-messaging
     - nova-conductor
     - nova-scheduler
     - oslo-messaging-zmq-receiver
     - python-zmq     
