###used to install a list of packages###
- hosts: controller
  tasks:
  - include: apt_get_update.yml
  - name: Install apt packages
    apt:
      pkg: "{{ item }}"
      state: latest
      force: yes
    register: install_packages
    until: install_packages|success
    sudo: yes
    with_items:
     - python-pyasn1
     - python-mysqldb
     - python-memcache
     - python-debtcollector
     - python-psutil
     - python-jinja2
     - python-lxml
     - python-rfc3986
     - python-boto
     - python-neutronclient
     - python-cinderclient
     - glance
     - glance-api
     - glance-common
     - glance-registry
     - nova-api
     - nova-cert
     - nova-common
     - nova-consoleauth
     - nova-novncproxy
     - python-glance
     - python-glanceclient
     - python-nova
     - python-novaclient
     - python-oslo-log
     - python-oslo-messaging
     - python-oslo-rootwrap
     - nova-conductor
     - nova-scheduler
     - oslo-messaging-zmq-receiver
     - python-zmq
     - apache2
  - include: controller_extension.yml

- hosts: cc*
  sudo: yes
  vars:
    ports:
      - 35357
      - 5000
      - 8773
      - 8774
      - 8776
  tasks:
  - include: controller_apache2.yml
