- hosts: cc*
  sudo: yes
  vars:
    apache2_cert_file: /etc/ssl/certs/jiocloud.com.crt
    apache2_key_file: /etc/ssl/keys/jiocloud.com.key
    apache2_chain_file: /etc/ssl/certs/gd_bundle-g2-g1.crt
    apache2_cert_path: /etc/ssl/certs
    apache_sites:
    - name: nova-ec2api
      site_port: 8773
      site_admin: root@localhost
      site_documentroot: nova-ec2api
      site_proxyport: 18773
    - name: nova-osapi
      site_port: 8774
      site_admin: root@localhost
      site_documentroot: nova-osapi
      site_proxyport: 18774
    - name: glance-api
      site_port: 9292
      site_admin: cloud.devops@ril.com
      site_documentroot: glance-api
      site_proxyport: 19292
    - name: glance-registry
      site_port: 9191
      site_admin: cloud.devops@ril.com
      site_documentroot: glance-registry
      site_proxyport: 19191
  tasks:
  - name: Copy config file
    template: src=templates/apache2_ports.conf dest=/etc/apache2/ports.conf

  - name: Remove sites-enabled
    shell: "rm -rf /etc/apache2/sites-enabled/*"

  - name: Add sites available
    template: src=templates/apache2-site.conf dest="/etc/apache2/sites-available/25-{{ item.name }}.conf"
    with_items: apache_sites

  - name: Add sites enabled
    shell: "ln -s /etc/apache2/sites-available/* /etc/apache2/sites-enabled"

  - include: jiocloud_ssl.yml

  - name: restart apache2
    service: name=apache2 state=restarted

