- hosts: csdb*
  sudo: yes
  tasks:
  - name: Install MariaDB repository
    apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu trusty main' state=present
  - name: Install Percona backaup repo
    apt_repository: repo='deb http://repo.percona.com/apt trusty main' state=present
  - name: Install MariaDB Server
    apt: name=mariadb-server state=latest update_cache=yes force=yes
  - name: Install python module
    apt: name=python-mysqldb state=installed

- hosts: csdb1
  sudo: yes
  tasks:
  - name: Create replication account
    mysql_user: name=repl host="%" password=lper priv="*.*:REPLICATION SLAVE,REPLICATION CLIENT" state=present
  - name: Create readwrite user
    mysql_user: name=rwuser host="%" password=adminpwd priv="*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,RELOAD,SUPER,REPLICATION CLIENT" state=present
  - name: Modify configuration file to listen on all interfaces
    lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="bind-address=0.0.0.0"

- hosts: csdb1
  sudo: yes
  tasks:
  - name: Modify configuration file to setup server ID
    lineinfile: dest=/etc/mysql/my.cnf regexp="^#server-id" line="server-id=1"
  - name: Restart mysql service
    service: name=mysql state=restarted


- hosts: csdb2
  sudo: yes
  tasks:
  - name: Modify configuration file to setup server ID
    lineinfile: dest=/etc/mysql/my.cnf regexp="^#server-id" line="server-id=2"
  - name: Start mysql service
    service: name=mysql state=restarted
  - name: Stop slave
    shell: /usr/bin/mysql -urwuser -padminpwd -e "STOP SLAVE " 
  - name: Setup replication
    #csdb1 must be updated to appropriate name.
    shell: /usr/bin/mysql -urwuser -padminpwd -e "CHANGE MASTER to master_host='csdb1', master_user='repl', master_password='lper', master_use_gtid=current_pos"
  - name: Start slave
    shell: /usr/bin/mysql -urwuser -padminpwd -e "START SLAVE " 
  - name: Restart mysql
    service: name=mysql state=restarted

