##This file is basically used to update apt resources as and when required



- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 600
  register: apt_update
  until: apt_update|success
  sudo: yes
